name: "test"
on: ["push", "pull_request"]

jobs:
  lint:
    name: "test"
    runs-on: ubuntu-latest
    steps:
    - name: "checkout"
      uses: actions/checkout@v4
      with:
        fetch-depth: 1
    - name: "setup Golang"
      uses: actions/setup-go@v5
    - name: "run tests"
      uses: make test
